create table "public"."user_contacts" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "email" text,
    "subject" text,
    "message" text,
    "answered" boolean default false,
    "is_anonymous" boolean default true
);


CREATE UNIQUE INDEX contacts_pkey ON public.user_contacts USING btree (id);

alter table "public"."user_contacts" add constraint "contacts_pkey" PRIMARY KEY using index "contacts_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.nearby_boards(lat double precision, lng double precision)
 RETURNS SETOF record
 LANGUAGE sql
AS $function$
  select
    id,
    name,
    json_build_object('lng', ST_X(location::geometry), 'lat', ST_Y(location::geometry)) as location,
    st_distance(location, st_point(lng, lat)::geography) as dist_meters
  from public.boards
  order by location <-> st_point(lng, lat)::geography;
$function$
;


