create extension if not exists "postgis" with schema "extensions";


create table "public"."boards" (
    "id" integer generated by default as identity not null,
    "name" text not null,
    "location" geography(Point,4326) not null
);


CREATE UNIQUE INDEX boards_pkey ON public.boards USING btree (id);

alter table "public"."boards" add constraint "boards_pkey" PRIMARY KEY using index "boards_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.nearby_boards(lat double precision, long double precision)
 RETURNS SETOF record
 LANGUAGE sql
AS $function$
  select id, name, st_astext(location) as location, st_distance(location, st_point(long, lat)::geography) as dist_meters
  from public.boards
  order by location <-> st_point(long, lat)::geography;
$function$
;


